<html>
<h1>Bienvenido al menu de pelis</h1>
<h2>Seleccione una opcion:</h2>

<ul>
    <li><a href=<?= $data['searchTitleLink']->getHref()?>>Buscar por titulo</a></li>
    <li><a href=<?= $data['searchActorLink']->getHref()?>>Buscar por Actor</a></li>
    <li><a href=<?= $data['searchDirectorLink']->getHref()?>>Buscar por Director</a></li>
    <li><a href=<?= $data['getCarteleraLink']->getHref()?>>Cartelera</a></li>
</ul>

</html>
